# Generated by Django 4.0.4 on 2022-11-26 20:32

import bankaccount.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_institution_id', models.CharField(max_length=254, unique=True, verbose_name='Plaid Institution ID')),
                ('name', models.CharField(max_length=254, verbose_name='Institution Name')),
                ('url', models.CharField(blank=True, max_length=254, verbose_name='Institution URL')),
            ],
            options={
                'verbose_name': 'Plaid Institution',
                'verbose_name_plural': 'Plaid Instituions',
            },
        ),
        migrations.CreateModel(
            name='UserPlaidLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', bankaccount.utils.EncryptedField(max_length=254, verbose_name='Access Code')),
                ('item_id', models.CharField(blank=True, max_length=254, null=True, verbose_name='Item ID')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bankaccount.plaidinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Plaid Link',
                'verbose_name_plural': 'User Plaid Links',
            },
        ),
        migrations.CreateModel(
            name='PlaidLinkAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('mask', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(max_length=50)),
                ('sub_type', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(max_length=10)),
                ('user_plaid_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccount.userplaidlink')),
            ],
        ),
        migrations.CreateModel(
            name='PlaidAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('merchant_name', models.CharField(max_length=254)),
                ('transaction_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('plaid_link_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccount.plaidlinkaccount')),
            ],
        ),
    ]
