# Generated by Django 4.0.4 on 2022-11-27 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plaidinstitution',
            options={'verbose_name': 'Plaid Institution', 'verbose_name_plural': 'Plaid Institutions'},
        ),
    ]
